import { faker } from '@faker-js/faker'

type FoodType =
  | 'cereals'
  | 'vegetables'
  | 'supplements'
  | 'custom'
  | 'grains'
  | 'greens'
  | 'nuts'

export type MacrosType = 'protein' | 'carbs' | 'fats' | 'cholesterol' | 'fiber'

export type MineralsType =
  | 'iron'
  | 'calcium'
  | 'sodium'
  | 'magnesium'
  | 'potassium'
  | 'manganese'
  | 'phosphorus'
  | 'copper'
  | 'zinc'

export type VitaminsType =
  | 'vitaminA'
  | 'vitaminC'
  | 'vitaminD'
  | 'vitaminE'
  | 'vitaminK'
  | 'riboflavin'
  | 'niacin'
  | 'pantothenicAcid'
  | 'vitaminB1'
  | 'vitaminB6'
  | 'vitaminB12'
  | 'folate'

export type AminoAcidsType =
  | 'tryptophan'
  | 'threonine'
  | 'isoleucine'
  | 'leucine'
  | 'lysine'
  | 'methionine'
  | 'cystine'
  | 'phenylalanine'
  | 'tyrosine'
  | 'valine'
  | 'histidine'

export type Unit = 'g' | 'mg'

type Macros = {
  type: Unit
  data: Record<MacrosType, number>
}

type Minerals = {
  type: Unit
  data: Record<MineralsType, number>
}

type Vitamins = {
  type: Unit
  data: Record<VitaminsType, number>
}

type AminoAcids = {
  type: Unit
  data: Record<AminoAcidsType, number>
}

export type FoodsType = {
  type: FoodType
  foodId: string
  name: string
  portion: number
  calories: number
  macros: Macros
  minerals: Minerals
  vitamins: Vitamins
  aminoAcids: AminoAcids
}

const database = [
  {
    type: 'cereals',
    foodId: faker.string.uuid(),
    name: 'Arroz Branco Cozido, Tipo 1',
    portion: 100,
    calories: 128,
    macros: {
      type: 'g',
      data: {
        protein: 2.5,
        carbs: 28.1,
        fats: 0.2,
        cholesterol: 0,
        fiber: 1.6,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.1,
        calcium: 4,
        sodium: 1,
        magnesium: 2,
        potassium: 15,
        manganese: 0.3,
        phosphorus: 18,
        copper: 0.02,
        zinc: 0.5,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.016,
        niacin: 0.4,
        pantothenicAcid: 0.411,
        biotin: 0,
        vitaminB1: 0.02,
        vitaminB6: 0.05,
        vitaminB12: 0,
        folate: 0.002,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 28,
        threonine: 85,
        isoleucine: 103,
        leucine: 197,
        lysine: 86,
        methionine: 56,
        cystine: 49,
        phenylalanine: 127,
        tyrosine: 80,
        valine: 145,
        histidine: 56,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Feijão Carioca Cozido',
    portion: 100,
    calories: 143,
    macros: {
      type: 'g',
      data: {
        protein: 9,
        carbs: 26.2,
        fats: 0.65,
        cholesterol: 0,
        fiber: 9,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 1.3,
        calcium: 27,
        sodium: 2,
        magnesium: 42,
        potassium: 255,
        manganese: 0.28,
        phosphorus: 87,
        copper: 0.19,
        zinc: 0.7,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0.8,
        vitaminD: 0,
        vitaminE: 0.94,
        vitaminK: 0.0035,
        riboflavin: 0.062,
        niacin: 0.318,
        pantothenicAcid: 0.21,
        vitaminB1: 0.193,
        vitaminB6: 0.229,
        vitaminB12: 0,
        folate: 0.172,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 108,
        threonine: 331,
        isoleucine: 426,
        leucine: 765,
        lysine: 630,
        methionine: 117,
        cystine: 84,
        phenylalanine: 531,
        tyrosine: 213,
        valine: 519,
        histidine: 247,
      },
    },
  },
  {
    type: 'grains',
    foodId: faker.string.uuid(),
    name: 'Lentilha Cozida',
    portion: 100,
    calories: 116,
    macros: {
      type: 'g',
      data: {
        protein: 9.02,
        carbs: 20.1,
        fats: 0.38,
        cholesterol: 0,
        fiber: 7.9,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 3.33,
        calcium: 19,
        sodium: 2,
        magnesium: 36,
        potassium: 369,
        manganese: 0.494,
        phosphorus: 180,
        copper: 0.251,
        zinc: 1.27,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 1.5,
        vitaminD: 0,
        vitaminE: 0.11,
        vitaminK: 0.0017,
        riboflavin: 0.073,
        niacin: 1.06,
        pantothenicAcid: 0.638,
        vitaminB1: 0.169,
        vitaminB6: 0.178,
        vitaminB12: 0,
        folate: 0.181,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 81,
        threonine: 323,
        isoleucine: 390,
        leucine: 654,
        lysine: 630,
        methionine: 77,
        cystine: 118,
        phenylalanine: 445,
        tyrosine: 241,
        valine: 448,
        histidine: 254,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Palmito Drenado',
    portion: 100,
    calories: 28,
    macros: {
      type: 'g',
      data: {
        protein: 2.52,
        carbs: 4.62,
        fats: 0.63,
        cholesterol: 0,
        fiber: 2.4,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 3.13,
        calcium: 58,
        sodium: 426,
        magnesium: 38,
        potassium: 117,
        manganese: 1.39,
        phosphorus: 65,
        copper: 0.133,
        zinc: 1.15,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 7.9,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.057,
        niacin: 0.473,
        pantothenicAcid: 0.126,
        vitaminB1: 0.011,
        vitaminB6: 0.022,
        vitaminB12: 0,
        folate: 0.039,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 23,
        threonine: 97,
        isoleucine: 101,
        leucine: 169,
        lysine: 91,
        methionine: 42,
        cystine: 19,
        phenylalanine: 98,
        tyrosine: 49,
        valine: 114,
        histidine: 55,
      },
    },
  },
  {
    type: 'custom',
    foodId: faker.string.uuid(),
    name: 'Macarrão de Arroz Sem Gluten',
    portion: 100,
    calories: 356,
    macros: {
      type: 'g',
      data: {
        protein: 7.25,
        carbs: 77.5,
        fats: 2.125,
        cholesterol: 0,
        fiber: 1.0,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.35,
        calcium: 10,
        sodium: 0,
        magnesium: 35,
        potassium: 76,
        manganese: 1.2,
        phosphorus: 98,
        copper: 0.13,
        zinc: 0.8,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.021,
        niacin: 2.59,
        pantothenicAcid: 0.819,
        vitaminB1: 0.138,
        vitaminB6: 0.436,
        vitaminB12: 0,
        folate: 0.004,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 72,
        threonine: 210,
        isoleucine: 244,
        leucine: 488,
        lysine: 207,
        methionine: 144,
        cystine: 107,
        phenylalanine: 317,
        tyrosine: 314,
        valine: 348,
        histidine: 149,
      },
    },
  },
  {
    type: 'supplements',
    foodId: faker.string.uuid(),
    name: 'Proteína de Soja Isolada',
    portion: 30,
    calories: 120,
    macros: {
      type: 'g',
      data: {
        protein: 27,
        carbs: 0,
        fats: 1.5,
        cholesterol: 0,
        fiber: 0,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 4.35,
        calcium: 53.4,
        sodium: 300,
        magnesium: 11.7,
        potassium: 24.3,
        manganese: 0.447,
        phosphorus: 232.8,
        copper: 0.48,
        zinc: 1.209,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.03,
        niacin: 0.432,
        pantothenicAcid: 0.018,
        vitaminB1: 0.0528,
        vitaminB6: 0.03,
        vitaminB12: 0,
        folate: 0.0528,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 330,
        threonine: 990,
        isoleucine: 600,
        leucine: 1810,
        lysine: 1980,
        methionine: 300,
        cystine: 370,
        phenylalanine: 1380,
        tyrosine: 1000,
        valine: 1010,
        histidine: 880,
      },
    },
  },
  {
    type: 'custom',
    foodId: faker.string.uuid(),
    name: 'Tofu',
    portion: 100,
    calories: 83,
    macros: {
      type: 'g',
      data: {
        protein: 9.98,
        carbs: 1.18,
        fats: 5.26,
        cholesterol: 0,
        fiber: 1.0,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 2.04,
        calcium: 282,
        sodium: 426,
        magnesium: 35,
        potassium: 130,
        manganese: 0.666,
        phosphorus: 111,
        copper: 0.2,
        zinc: 1.07,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0.0028,
        riboflavin: 0.048,
        niacin: 0.241,
        pantothenicAcid: 0.844,
        vitaminB1: 0.048,
        vitaminB6: 0.083,
        vitaminB12: 0,
        folate: 0.009,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 135,
        threonine: 453,
        isoleucine: 490,
        leucine: 804,
        lysine: 510,
        methionine: 122,
        cystine: 33,
        phenylalanine: 482,
        tyrosine: 405,
        valine: 503,
        histidine: 249,
      },
    },
  },
  {
    type: 'grains',
    foodId: faker.string.uuid(),
    name: 'Grão de Bico Cozido',
    portion: 100,
    calories: 152,
    macros: {
      type: 'g',
      data: {
        protein: 8.7,
        carbs: 27.2,
        fats: 0.54,
        cholesterol: 0,
        fiber: 17.4,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 1.74,
        calcium: 33,
        sodium: 304,
        magnesium: 47.98,
        potassium: 293,
        manganese: 0,
        phosphorus: 167,
        copper: 0,
        zinc: 2.5,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.0,
        vitaminC: 2.1,
        vitaminD: 0,
        vitaminE: 0.6,
        vitaminK: 0.06,
        riboflavin: 0.0,
        niacin: 0,
        pantothenicAcid: 0,
        vitaminB1: 0,
        vitaminB6: 0,
        vitaminB12: 0,
        folate: 0,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 85,
        threonine: 329,
        isoleucine: 380,
        leucine: 631,
        lysine: 593,
        methionine: 116,
        cystine: 119,
        phenylalanine: 475,
        tyrosine: 220,
        valine: 372,
        histidine: 244,
      },
    },
  },
  {
    type: 'greens',
    foodId: faker.string.uuid(),
    name: 'Alface',
    portion: 100,
    calories: 15,
    macros: {
      type: 'g',
      data: {
        protein: 1.36,
        carbs: 2.87,
        fats: 0.15,
        cholesterol: 0,
        fiber: 1.3,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.86,
        calcium: 36,
        sodium: 28,
        magnesium: 13,
        potassium: 194,
        manganese: 0.25,
        phosphorus: 29,
        copper: 0.029,
        zinc: 0.18,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 9.2,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0.126,
        riboflavin: 0.08,
        niacin: 0.375,
        pantothenicAcid: 0.134,
        vitaminB1: 0.07,
        vitaminB6: 0.09,
        vitaminB12: 0,
        folate: 0.038,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 9,
        threonine: 59,
        isoleucine: 84,
        leucine: 79,
        lysine: 84,
        methionine: 16,
        cystine: 16,
        phenylalanine: 55,
        tyrosine: 32,
        valine: 70,
        histidine: 22,
      },
    },
  },
  {
    type: 'greens',
    foodId: faker.string.uuid(),
    name: 'Espinafre',
    portion: 100,
    calories: 23,
    macros: {
      type: 'g',
      data: {
        protein: 2.86,
        carbs: 3.63,
        fats: 0.39,
        cholesterol: 0,
        fiber: 2.2,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 2.71,
        calcium: 99,
        sodium: 79,
        magnesium: 79,
        potassium: 558,
        manganese: 0.897,
        phosphorus: 49,
        copper: 0.13,
        zinc: 0.53,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.469,
        vitaminC: 28.1,
        vitaminD: 0,
        vitaminE: 2.03,
        vitaminK: 0.483,
        riboflavin: 0.189,
        niacin: 0.724,
        pantothenicAcid: 0.065,
        vitaminB1: 0.078,
        vitaminB6: 0.195,
        vitaminB12: 0,
        folate: 0.194,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 39,
        threonine: 122,
        isoleucine: 147,
        leucine: 223,
        lysine: 174,
        methionine: 53,
        cystine: 35,
        phenylalanine: 129,
        tyrosine: 108,
        valine: 161,
        histidine: 64,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Brocolis',
    portion: 100,
    calories: 35,
    macros: {
      type: 'g',
      data: {
        protein: 2.4,
        carbs: 7.2,
        fats: 0.4,
        cholesterol: 0,
        fiber: 3.3,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.7,
        calcium: 40,
        sodium: 262,
        magnesium: 21,
        potassium: 293,
        manganese: 0.2,
        phosphorus: 67,
        copper: 0.1,
        zinc: 0.5,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.077,
        vitaminC: 64.9,
        vitaminD: 0,
        vitaminE: 1.5,
        vitaminK: 0.141,
        riboflavin: 0.1,
        niacin: 0.6,
        pantothenicAcid: 0.6,
        vitaminB1: 0.1,
        vitaminB6: 0.2,
        vitaminB12: 0,
        folate: 0,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 33,
        threonine: 88,
        isoleucine: 79,
        leucine: 129,
        lysine: 135,
        methionine: 38,
        cystine: 28,
        phenylalanine: 117,
        tyrosine: 50,
        valine: 125,
        histidine: 59,
      },
    },
  },
  {
    type: 'greens',
    foodId: faker.string.uuid(),
    name: 'Couve',
    portion: 100,
    calories: 38,
    macros: {
      type: 'g',
      data: {
        protein: 3.13,
        carbs: 4.74,
        fats: 1.6,
        cholesterol: 0,
        fiber: 4.4,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 1.72,
        calcium: 272,
        sodium: 181,
        magnesium: 35,
        potassium: 373,
        manganese: 0,
        phosphorus: 59,
        copper: 0.057,
        zinc: 0.42,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.245,
        vitaminC: 70.1,
        vitaminD: 0,
        vitaminE: 1.5,
        vitaminK: 0.418,
        riboflavin: 0.1,
        niacin: 0.6,
        pantothenicAcid: 0.6,
        vitaminB1: 0.109,
        vitaminB6: 0.15,
        vitaminB12: 0,
        folate: 0.05,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 35,
        threonine: 131,
        isoleucine: 175,
        leucine: 205,
        lysine: 175,
        methionine: 29,
        cystine: 38,
        phenylalanine: 150,
        tyrosine: 103,
        valine: 159,
        histidine: 172,
      },
    },
  },
  {
    type: 'greens',
    foodId: faker.string.uuid(),
    name: 'Repolho',
    portion: 100,
    calories: 23,
    macros: {
      type: 'g',
      data: {
        protein: 1.27,
        carbs: 5.51,
        fats: 0.06,
        cholesterol: 0,
        fiber: 1.9,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.17,
        calcium: 48,
        sodium: 8,
        magnesium: 15,
        potassium: 196,
        manganese: 0.205,
        phosphorus: 33,
        copper: 0.017,
        zinc: 0.2,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.004,
        vitaminC: 37.5,
        vitaminD: 0,
        vitaminE: 0.14,
        vitaminK: 0.109,
        riboflavin: 0.038,
        niacin: 0.248,
        pantothenicAcid: 0.174,
        vitaminB1: 0.061,
        vitaminB6: 0.112,
        vitaminB12: 0,
        folate: 0.03,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 11,
        threonine: 35,
        isoleucine: 30,
        leucine: 41,
        lysine: 43,
        methionine: 12,
        cystine: 11,
        phenylalanine: 32,
        tyrosine: 19,
        valine: 42,
        histidine: 22,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Tomate',
    portion: 100,
    calories: 18,
    macros: {
      type: 'g',
      data: {
        protein: 0.88,
        carbs: 3.89,
        fats: 0.2,
        cholesterol: 0,
        fiber: 1.2,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.27,
        calcium: 10,
        sodium: 5,
        magnesium: 11,
        potassium: 237,
        manganese: 0.114,
        phosphorus: 24,
        copper: 0.059,
        zinc: 0.17,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 13.7,
        vitaminD: 0,
        vitaminE: 0.54,
        vitaminK: 0.0079,
        riboflavin: 0.019,
        niacin: 0.594,
        pantothenicAcid: 0.089,
        vitaminB1: 0.037,
        vitaminB6: 0.08,
        vitaminB12: 0,
        folate: 0.015,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 6,
        threonine: 27,
        isoleucine: 18,
        leucine: 25,
        lysine: 27,
        methionine: 6,
        cystine: 9,
        phenylalanine: 27,
        tyrosine: 14,
        valine: 18,
        histidine: 14,
      },
    },
  },
  {
    type: 'cereal',
    foodId: faker.string.uuid(),
    name: 'Aveia',
    portion: 100,
    calories: 379,
    macros: {
      type: 'g',
      data: {
        protein: 13.15,
        carbs: 67.7,
        fats: 6.52,
        cholesterol: 0,
        fiber: 0.01,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 4.25,
        calcium: 52,
        sodium: 6,
        magnesium: 138,
        potassium: 362,
        manganese: 0,
        phosphorus: 410,
        copper: 0.391,
        zinc: 3.64,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0.002,
        riboflavin: 0.115,
        niacin: 1.125,
        pantothenicAcid: 0,
        vitaminB1: 0.46,
        vitaminB6: 0.1,
        vitaminB12: 0,
        folate: 0.032,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 234,
        threonine: 575,
        isoleucine: 694,
        leucine: 1.28,
        lysine: 701,
        methionine: 312,
        cystine: 408,
        phenylalanine: 895,
        tyrosine: 573,
        valine: 937,
        histidine: 405,
      },
    },
  },
  {
    type: 'nuts',
    foodId: faker.string.uuid(),
    name: 'Castanha de Caju',
    portion: 100,
    calories: 553,
    macros: {
      type: 'g',
      data: {
        protein: 18.2,
        carbs: 30.2,
        fats: 43.8,
        cholesterol: 0,
        fiber: 3.3,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 6.68,
        calcium: 37,
        sodium: 12,
        magnesium: 292,
        potassium: 660,
        manganese: 1.66,
        phosphorus: 593,
        copper: 2.2,
        zinc: 5.78,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0.5,
        vitaminD: 0,
        vitaminE: 0.9,
        vitaminK: 0.0341,
        riboflavin: 0.058,
        niacin: 1.06,
        pantothenicAcid: 0.864,
        vitaminB1: 0.423,
        vitaminB6: 0.417,
        vitaminB12: 0,
        folate: 0.025,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 287,
        threonine: 688,
        isoleucine: 789,
        leucine: 1470,
        lysine: 928,
        methionine: 362,
        cystine: 393,
        phenylalanine: 951,
        tyrosine: 508,
        valine: 1090,
        histidine: 456,
      },
    },
  },
  {
    type: 'nuts',
    foodId: faker.string.uuid(),
    name: 'Amendoas',
    portion: 100,
    calories: 579,
    macros: {
      type: 'g',
      data: {
        protein: 21.2,
        carbs: 21.6,
        fats: 49.9,
        cholesterol: 0,
        fiber: 12.5,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 3.71,
        calcium: 269,
        sodium: 1,
        magnesium: 270,
        potassium: 733,
        manganese: 2.18,
        phosphorus: 481,
        copper: 1.03,
        zinc: 3.12,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 25.6,
        vitaminK: 0,
        riboflavin: 1.14,
        niacin: 3.62,
        pantothenicAcid: 0.471,
        vitaminB1: 0.205,
        vitaminB6: 0.137,
        vitaminB12: 0,
        folate: 0.044,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 211,
        threonine: 601,
        isoleucine: 751,
        leucine: 1470,
        lysine: 568,
        methionine: 157,
        cystine: 215,
        phenylalanine: 1130,
        tyrosine: 450,
        valine: 855,
        histidine: 539,
      },
    },
  },
  {
    type: 'nuts',
    foodId: faker.string.uuid(),
    name: 'Castanha do Pará',
    portion: 100,
    calories: 659,
    macros: {
      type: 'g',
      data: {
        protein: 14.32,
        carbs: 11.74,
        fats: 67.1,
        cholesterol: 0,
        fiber: 7.5,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 2.43,
        calcium: 160,
        sodium: 3,
        magnesium: 376,
        potassium: 659,
        manganese: 0,
        phosphorus: 725,
        copper: 1.743,
        zinc: 4.06,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0.7,
        vitaminD: 0,
        vitaminE: 5.65,
        vitaminK: 0,
        riboflavin: 0.035,
        niacin: 0.295,
        pantothenicAcid: 0,
        vitaminB1: 0.617,
        vitaminB6: 0.101,
        vitaminB12: 0,
        folate: 0.022,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 100,
        threonine: 400,
        isoleucine: 500,
        leucine: 1200,
        lysine: 500,
        methionine: 1100,
        cystine: 300,
        phenylalanine: 600,
        tyrosine: 400,
        valine: 800,
        histidine: 400,
      },
    },
  },
  {
    type: 'nuts',
    foodId: faker.string.uuid(),
    name: 'Amendoim',
    portion: 100,
    calories: 567,
    macros: {
      type: 'g',
      data: {
        protein: 25.8,
        carbs: 16.1,
        fats: 49.2,
        cholesterol: 0,
        fiber: 8.5,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 4.58,
        calcium: 92,
        sodium: 18,
        magnesium: 168,
        potassium: 705,
        manganese: 1.93,
        phosphorus: 376,
        copper: 1.14,
        zinc: 3.27,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.135,
        niacin: 12.1,
        pantothenicAcid: 1.77,
        vitaminB1: 0.64,
        vitaminB6: 0.348,
        vitaminB12: 0,
        folate: 0.024,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 250,
        threonine: 883,
        isoleucine: 907,
        leucine: 1670,
        lysine: 926,
        methionine: 317,
        cystine: 331,
        phenylalanine: 1380,
        tyrosine: 1050,
        valine: 1080,
        histidine: 652,
      },
    },
  },
  {
    type: 'supplements',
    foodId: faker.string.uuid(),
    name: 'Leite Castanha do Para',
    portion: 200,
    calories: 113,
    macros: {
      type: 'g',
      data: {
        protein: 5.9,
        carbs: 10,
        fats: 6,
        cholesterol: 0,
        fiber: 0.6,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 1.0,
        calcium: 263,
        sodium: 134,
        magnesium: 34,
        potassium: 61,
        manganese: 0.1,
        phosphorus: 103,
        copper: 0.2,
        zinc: 0.6,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0.1,
        vitaminD: 0,
        vitaminE: 0.5,
        vitaminK: 0,
        riboflavin: 0,
        niacin: 0.1,
        pantothenicAcid: 0,
        vitaminB1: 0,
        vitaminB6: 0,
        vitaminB12: 0,
        folate: 0,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 65,
        threonine: 206,
        isoleucine: 147,
        leucine: 417,
        lysine: 386,
        methionine: 147,
        cystine: 90,
        phenylalanine: 291,
        tyrosine: 208,
        valine: 244,
        histidine: 187,
      },
    },
  },
  {
    type: 'supplements',
    foodId: faker.string.uuid(),
    name: 'Leite Castanha de Caju',
    portion: 200,
    calories: 112,
    macros: {
      type: 'g',
      data: {
        protein: 6.0,
        carbs: 10,
        fats: 5.9,
        cholesterol: 0,
        fiber: 0.4,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 1.4,
        calcium: 252,
        sodium: 122,
        magnesium: 39.5,
        potassium: 89,
        manganese: 0.3,
        phosphorus: 108,
        copper: 0.4,
        zinc: 0.9,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.1,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0.1,
        vitaminK: 0,
        riboflavin: 0,
        niacin: 0.2,
        pantothenicAcid: 0.1,
        vitaminB1: 0.1,
        vitaminB6: 0.1,
        vitaminB12: 0,
        folate: 0,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 81,
        threonine: 221,
        isoleucine: 183,
        leucine: 432,
        lysine: 384,
        methionine: 87,
        cystine: 100,
        phenylalanine: 308,
        tyrosine: 199,
        valine: 276,
        histidine: 177,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Batata Cozida',
    portion: 100,
    calories: 87,
    macros: {
      type: 'g',
      data: {
        protein: 1.87,
        carbs: 20.1,
        fats: 0.1,
        cholesterol: 0,
        fiber: 1.8,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.31,
        calcium: 5,
        sodium: 4,
        magnesium: 22,
        potassium: 379,
        manganese: 0.138,
        phosphorus: 44,
        copper: 0.188,
        zinc: 0.3,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 13,
        vitaminD: 0,
        vitaminE: 0.01,
        vitaminK: 0.0022,
        riboflavin: 0.02,
        niacin: 1.44,
        pantothenicAcid: 0.52,
        vitaminB1: 0.106,
        vitaminB6: 0.299,
        vitaminB12: 0,
        folate: 0.01,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 29,
        threonine: 68,
        isoleucine: 76,
        leucine: 112,
        lysine: 114,
        methionine: 30,
        cystine: 24,
        phenylalanine: 83,
        tyrosine: 69,
        valine: 105,
        histidine: 41,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Mandioca Cozida',
    portion: 100,
    calories: 191,
    macros: {
      type: 'g',
      data: {
        protein: 1.42,
        carbs: 39.62,
        fats: 3.02,
        cholesterol: 2,
        fiber: 1.9,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.28,
        calcium: 17,
        sodium: 146,
        magnesium: 22,
        potassium: 282,
        manganese: 0,
        phosphorus: 28,
        copper: 0.104,
        zinc: 0.36,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0.0013,
        vitaminC: 18.2,
        vitaminD: 0,
        vitaminE: 0.01,
        vitaminK: 0.0045,
        riboflavin: 0.048,
        niacin: 0.845,
        pantothenicAcid: 0,
        vitaminB1: 0.082,
        vitaminB6: 0.1,
        vitaminB12: 0,
        folate: 0.024,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 19,
        threonine: 28,
        isoleucine: 27,
        leucine: 39,
        lysine: 44,
        methionine: 11,
        cystine: 28,
        phenylalanine: 26,
        tyrosine: 17,
        valine: 35,
        histidine: 20,
      },
    },
  },
  {
    type: 'custom',
    foodId: faker.string.uuid(),
    name: 'Bife Frango Vegano',
    portion: 100,
    calories: 147,
    macros: {
      type: 'g',
      data: {
        protein: 30.5,
        carbs: 3.1,
        fats: 2.0,
        cholesterol: 0,
        fiber: 1.6,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 6.8,
        calcium: 96.4,
        sodium: 609.7,
        magnesium: 38.3,
        potassium: 146.3,
        manganese: 1.4,
        phosphorus: 292.5,
        copper: 0.6,
        zinc: 2.1,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 5.4,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.07,
        niacin: 0.76,
        pantothenicAcid: 0.1,
        vitaminB1: 0.06,
        vitaminB6: 0.05,
        vitaminB12: 0,
        folate: 0.08,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 368,
        threonine: 1122,
        isoleucine: 709,
        leucine: 2046,
        lysine: 2174,
        methionine: 349,
        cystine: 408,
        phenylalanine: 1539,
        tyrosine: 1100,
        valine: 1155,
        histidine: 976,
      },
    },
  },
  {
    type: 'grains',
    foodId: faker.string.uuid(),
    name: 'PTS Proteína Texturizada de Soja',
    portion: 100,
    calories: 270,
    macros: {
      type: 'g',
      data: {
        protein: 52,
        carbs: 30,
        fats: 4.0,
        cholesterol: 0,
        fiber: 4.0,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 10,
        calcium: 320,
        sodium: 609.7,
        magnesium: 300,
        potassium: 2400,
        manganese: 5,
        phosphorus: 730,
        copper: 2,
        zinc: 5,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0.31,
        niacin: 2.6,
        pantothenicAcid: 0,
        vitaminB1: 0,
        vitaminB6: 0.5,
        vitaminB12: 0,
        folate: 0.3,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 1200,
        threonine: 3800,
        isoleucine: 4700,
        leucine: 7700,
        lysine: 6500,
        methionine: 1300,
        cystine: 1400,
        phenylalanine: 4900,
        tyrosine: 3400,
        valine: 4900,
        histidine: 2600,
      },
    },
  },
  {
    type: 'vegetables',
    foodId: faker.string.uuid(),
    name: 'Batata Doce',
    portion: 100,
    calories: 90,
    macros: {
      type: 'g',
      data: {
        protein: 2.01,
        carbs: 20.71,
        fats: 0,
        cholesterol: 0,
        fiber: 3.3,
      },
    },
    minerals: {
      type: 'mg',
      data: {
        iron: 0.8,
        calcium: 18,
        sodium: 36,
        magnesium: 0,
        potassium: 475,
        manganese: 0,
        phosphorus: 0,
        copper: 0,
        zinc: 0,
      },
    },
    vitamins: {
      type: 'mg',
      data: {
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        riboflavin: 0,
        niacin: 0,
        pantothenicAcid: 0,
        vitaminB1: 0,
        vitaminB6: 0,
        vitaminB12: 0,
        folate: 0,
      },
    },
    aminoAcids: {
      type: 'mg',
      data: {
        tryptophan: 0,
        threonine: 0,
        isoleucine: 0,
        leucine: 0,
        lysine: 0,
        methionine: 0,
        cystine: 0,
        phenylalanine: 0,
        tyrosine: 0,
        valine: 0,
        histidine: 0,
      },
    },
  },
] as FoodsType[]

export default database
